Update config.yml

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -45,20 +45,20 @@ install: &install
     - restore_cache:
         <<: *cache_keys
     - run: echo $MAVEN_OPTS && echo $CIRCLE_WORKING_DIRECTORY && pwd && ls -alF
-    - run: |
-        mkdir -p ~/.m2 && cp settings.xml ~/.m2/settings.xml
-        rm -rf ~/.m2/build ~/.m2/repository/io/opentracing/contrib/specialagent
-        export MAVEN_OPTS="-Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn"
-        mvn -B -P test --fail-at-end -Dsilent dependency:go-offline || true
-        if [ "$CIRCLE_BRANCH" = "XXX-master-XXX" ] &&
-           [ "$CIRCLE_PULL_REQUEST" = "" ]; then
-          mvn -e -B -P report install &&
-          mvn -e -B -DrepoToken=$REPO_TOKEN coveralls:report &&
-          mvn -e -B -Dassemble install;
-        else
-          mvn -e -B -DskipTests install &&
-          mvn -e -B -DignoreMissingTestManifest -Dassemble install;
-        fi
+#    - run: |
+#        mkdir -p ~/.m2 && cp settings.xml ~/.m2/settings.xml
+#        rm -rf ~/.m2/build ~/.m2/repository/io/opentracing/contrib/specialagent
+#        export MAVEN_OPTS="-Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn"
+#        mvn -B -P test --fail-at-end -Dsilent dependency:go-offline || true
+#        if [ "$CIRCLE_BRANCH" = "XXX-master-XXX" ] &&
+#           [ "$CIRCLE_PULL_REQUEST" = "" ]; then
+#          mvn -e -B -P report install &&
+#          mvn -e -B -DrepoToken=$REPO_TOKEN coveralls:report &&
+#          mvn -e -B -Dassemble install;
+#        else
+#          mvn -e -B -DskipTests install &&
+#          mvn -e -B -DignoreMissingTestManifest -Dassemble install;
+#        fi
     - save_cache:
         key: specialagent-{{ checksum "pom.xml" }}-{{ .Branch }}-{{ .Revision }}
         paths: ~/.m2
@@ -66,6 +66,7 @@ install: &install
         root: .
         paths:
           - .
+          - ~/.m2
 
 test: &test
   parallelism: 4
@@ -74,7 +75,8 @@ test: &test
         at: .
     - run:
         command: |
-          circleci tests glob "test/*/pom.xml" | sed 's/\/pom.xml//' | awk '{print "ls -alF && mvn -e -B -P test -pl " $1 " -amd test-compile"}' | circleci tests split > /tmp/tests-to-run
+          mv .m2 ~
+          circleci tests glob "test/*/pom.xml" | sed 's/\/pom.xml//' | awk '{print "ls -alF ~/.m2 && mvn -e -B -P test -pl " $1 " -amd test-compile"}' | circleci tests split > /tmp/tests-to-run
           cat /tmp/tests-to-run
           bash -c "$(cat /tmp/tests-to-run)"
 
